'use client'
import { useState } from 'react'
import Link from 'next/link'
import { createClient } from '../../../lib/supabase/client'

export default function LoginPage(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [mode,setMode]=useState<'sign-in'|'sign-up'>('sign-in'); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError('');setMessage('');const supabase=createClient();if(!supabase){setError('Authentication is not configured for this deployment.');setLoading(false);return}const result=mode==='sign-in'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL??`${window.location.origin}/auth/callback`}});if(result.error){setError(mode==='sign-in'?'Invalid email or password.':'Unable to create your account. Check your email and password.')}else if(mode==='sign-up'){setMessage('Check your email to confirm your account, then sign in.')}else{window.location.href='/app'}setLoading(false)}
  return <main className="auth-page"><div className="auth-card"><Link href="/" className="brand-lockup"><span className="brand-mark">H</span><span>HackNex <b>Live</b></span></Link><p className="eyebrow">PRIVATE WORKSPACE</p><h1>{mode==='sign-in'?'Welcome back.':'Create your workspace.'}</h1><p className="page-lede">Sign in to access your live translation room, saved preferences, and usage history.</p><form onSubmit={submit} className="auth-form"><label htmlFor="email">Email<input id="email" type="email" autoComplete="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label htmlFor="password">Password<input id="password" type="password" autoComplete={mode==='sign-in'?'current-password':'new-password'} minLength={6} required value={password} onChange={event=>setPassword(event.target.value)}/></label><button className="primary-button auth-button" type="submit" disabled={loading}>{loading?'Connecting…':mode==='sign-in'?'Sign in →':'Create account →'}</button></form>{error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="auth-success" role="status">{message}</p>}<button className="auth-switch" type="button" onClick={()=>{setMode(mode==='sign-in'?'sign-up':'sign-in');setError('');setMessage('')}}>{mode==='sign-in'?"Don't have an account? Create one":"Already have an account? Sign in"}</button><p className="auth-note">By continuing, you agree to our <Link href="/terms">Terms</Link> and <Link href="/privacy">Privacy Policy</Link>.</p></div></main>}
