'use client'
import { useEffect, useRef, useState, type ChangeEvent } from 'react'
import Link from 'next/link'
import { getSupabaseClient } from '../../lib/supabase'
import { createRoomId, createTranslationAdapter, formatEventTime, formatMetric, audioFileIsWav, supportedLanguages, type TranslationEvent } from '../../lib/translation/client'

export default function LiveRoom() {
 const [userReady,setUserReady]=useState(false),[userEmail,setUserEmail]=useState('')
 const [live,setLive]=useState(false),[source,setSource]=useState('Tamil'),[target,setTarget]=useState('English'),[auto,setAuto]=useState(false),[detected,setDetected]=useState(''),[segments,setSegments]=useState<{source:string;translation:string;partial:boolean;time:string;confidence?:number}[]>([]),[error,setError]=useState(''),[level,setLevel]=useState(0),[first,setFirst]=useState<number>(),[final,setFinal]=useState<number>(),[terms,setTerms]=useState<string[]>([]),[term,setTerm]=useState(''),[consent,setConsent]=useState(false),[room,setRoom]=useState('')
 const adapter=useRef(createTranslationAdapter()), stream=useRef<MediaStream | null>(null), recorder=useRef<MediaRecorder | null>(null)
 useEffect(()=>{getSupabaseClient().auth.getUser().then(({data})=>{setUserEmail(data.user?.email??'');setUserReady(Boolean(data.user))});return()=>stream.current?.getTracks().forEach(t=>t.stop())},[])
 function handleEvent(e:TranslationEvent){if(e.type==='language_detected')setDetected(e.language);if(e.type==='metrics'){setFirst(e.timeToFirstWordMs);setFinal(e.endOfSpeechToFinalMs)}if(e.type==='error')setError(e.message);if(['partial_source','partial_translation','committed_translation','final_translation'].includes(e.type)){const text='text' in e?e.text:'';setSegments(s=>{const last=s.at(-1);const next={source:last?.source??'',translation:last?.translation??'',partial:e.type.startsWith('partial'),time:formatEventTime(e.timestampMs),confidence:'confidence' in e?e.confidence:undefined};if(e.type.includes('source'))next.source=text;else next.translation=text;return last?.partial?[...s.slice(0,-1),next]:[...s,next]})}}
 async function start(){setError('');if(!consent){setError('Please accept recording consent before starting.');return}if(!navigator.mediaDevices?.getUserMedia){setError('This browser does not support microphone capture.');return}try{const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;const r=new MediaRecorder(s);recorder.current=r;r.ondataavailable=async e=>{if(e.data.size)adapter.current.sendAudio(await e.data.arrayBuffer())};r.start(250);adapter.current.onEvent(handleEvent);await adapter.current.connect({sourceLanguage:source,targetLanguage:target,glossary:terms,autoDetect:auto});setRoom(createRoomId());setLive(true);setLevel(38)}catch(e){setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Microphone permission was denied. Allow access and try again.':'Unable to start microphone capture.')}}
 async function stop(){recorder.current?.stop();stream.current?.getTracks().forEach(t=>t.stop());await adapter.current.end();setLive(false);setLevel(0)}
 async function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!audioFileIsWav(f)){setError('Please choose a WAV file.');return}if(!consent){setError('Please accept recording consent before uploading.');return}setError('');await adapter.current.connect({sourceLanguage:source,targetLanguage:target,glossary:terms,autoDetect:auto});adapter.current.sendAudio(await f.arrayBuffer());setLive(true);setRoom(createRoomId())}
 if (!userReady) return <main className="app-shell"><section className="workspace"><p className="eyebrow">ACCOUNT CHECK</p><h1>Checking your session.</h1></section></main>
 if (!userEmail) return <main className="app-shell"><section className="workspace"><p className="eyebrow">PROTECTED LIVE ROOM</p><h1>Sign in to translate.</h1><p className="subhead">Your transcripts and usage belong to your account.</p><Link className="primary-button" href="/auth/login">Sign in</Link></section></main>
 return <main className="app-shell"><header className="topbar"><div className="brand-lockup"><span className="brand-mark">H</span><span>HackNex <b>Live</b></span></div><nav className="main-nav"><Link href="/">Home</Link><Link className="nav-active" href="/app">Live room</Link><Link href="/results">Results</Link><Link href="/compare">Compare</Link><Link href="/status">Status</Link></nav><span>{room}</span></header><section className="workspace"><p className="eyebrow">LIVE TRANSLATION ROOM</p><h1>Make space for every voice.</h1><div className="language-bar"><label>Speaking<select value={source} onChange={e=>setSource(e.target.value)}>{supportedLanguages.map(x=><option key={x}>{x}</option>)}</select></label><label>Translate to<select value={target} onChange={e=>setTarget(e.target.value)}>{supportedLanguages.map(x=><option key={x}>{x}</option>)}</select></label><label className="check-row"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Auto-detect</label>{detected&&<span className="chip">Detected: {detected}</span>}</div><div className="heading-actions"><button className="primary-button" onClick={live?stop:start}>{live?'Stop microphone':'Start microphone'}</button><label className="ghost-button">Upload WAV<input hidden type="file" accept="audio/wav,.wav" onChange={upload}/></label><label className="check-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to recording</label></div>{error&&<p className="error-message" role="alert">{error}</p>}<div className="feature-strip"><div><b>Microphone level</b><small>{level ? 'Capturing audio' : 'Idle'}</small><progress max="100" value={level}/></div><div><b>Time to first word</b><small>{formatMetric(first)}</small></div><div><b>End of speech → final</b><small>{formatMetric(final)}</small></div><span>{live?'Live adapter':'Demo recording'}</span></div><section className="panel"><h2>{live?'Live captions':'Demo recording'}</h2>{(live?segments:[{source:'இன்று நாம் மொழிகளுக்கு இடையே உள்ள தடைகளை உடைக்கிறோம்.',translation:'Today, we are breaking the barriers between languages.',partial:false,time:'00:02'}]).map((s,i)=><article className={s.partial?'caption provisional':'caption'} key={i}><small>{s.time}</small><p>{s.source}</p><strong>{s.translation}</strong>{s.confidence!=null&&<small>{Math.round(s.confidence*100)}% confidence</small>}</article>)}</section><section className="panel"><h2>Glossary</h2><div className="heading-actions"><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Add a term"/><button className="ghost-button" onClick={()=>{if(term.trim())setTerms([...terms,term.trim()]);setTerm('')}}>Add</button></div>{terms.map(t=><button className="chip" key={t} onClick={()=>setTerms(terms.filter(x=>x!==t))}>{t} ×</button>)}</section></section></main>
}
